# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogs',
            name='raw_details',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Details'),
        ),
    ]
